name: qrcode_reader_web
description: This library aims to read QR Codes on the web. With it, you can use the device's camera to scan QR codes and perform various actions with the obtained data.
version: 1.0.2
homepage: https://github.com/GabrielDimaa/qrcode_reader_web

environment:
  sdk: '>=2.19.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: QRCodeReader
        fileName: src/qrcode_reader.dart