name: qrcode_reader_web
description: Esta biblioteca tem como objetivo ler QR Codes na Web. Com ele, é possível utilizar a câmera do dispositivo para escanear QR codes e realizar diversas ações com os dados obtidos.
version: 1.0.0
homepage: https://github.com/GabrielDimaa/qrcode_reader_web

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: QRCodeReader
        fileName: src/qrcode_reader.dart